// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains(id, created_at, updated_at, owner, name)
VALUES(
    GEN_RANDOM_UUID(), 
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, owner, name
`

type CreateDomainParams struct {
	Owner uuid.UUID
	Name  string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.Owner, arg.Name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
		&i.Name,
	)
	return i, err
}
