// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserToDomain = `-- name: AddUserToDomain :exec

INSERT INTO domains_users(domain_id, user_id)
VALUES(
    $1, 
    $2
)
`

type AddUserToDomainParams struct {
	DomainID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) AddUserToDomain(ctx context.Context, arg AddUserToDomainParams) error {
	_, err := q.db.ExecContext(ctx, addUserToDomain, arg.DomainID, arg.UserID)
	return err
}

const deleteAllUsersFromDomains = `-- name: DeleteAllUsersFromDomains :exec

DELETE FROM domains_users
`

func (q *Queries) DeleteAllUsersFromDomains(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsersFromDomains)
	return err
}
