// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains(id, created_at, updated_at, owner, name)
VALUES(
    GEN_RANDOM_UUID(), 
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, owner, name
`

type CreateDomainParams struct {
	Owner uuid.UUID
	Name  string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.Owner, arg.Name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
		&i.Name,
	)
	return i, err
}

const deleteAllDomains = `-- name: DeleteAllDomains :exec

DELETE FROM domains
`

func (q *Queries) DeleteAllDomains(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDomains)
	return err
}

const getDomainByID = `-- name: GetDomainByID :one

SELECT id, created_at, updated_at, owner, name FROM domains 
WHERE id = $1
`

func (q *Queries) GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Owner,
		&i.Name,
	)
	return i, err
}

const getUserDomains = `-- name: GetUserDomains :many

WITH domain_ids AS (
    SELECT domain_id FROM domains_users
    WHERE user_id = $1
)
SELECT domains.id, domains.created_at, domains.updated_at, domains.owner, domains.name FROM domains JOIN domain_ids
ON domains.id = domain_ids.domain_id
`

func (q *Queries) GetUserDomains(ctx context.Context, userID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, getUserDomains, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Owner,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
