// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Domain struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Owner     uuid.UUID
	Name      string
}

type DomainsUser struct {
	DomainID uuid.UUID
	UserID   uuid.UUID
}

type Task struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
	DomainID    uuid.UUID
	AssigneeID  uuid.UUID
	CompletedAt sql.NullTime
}

type TaskDependency struct {
	TaskID       uuid.UUID
	DependencyID uuid.UUID
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	DisplayName string
}
