// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_dependencies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTaskDependency = `-- name: CreateTaskDependency :exec

INSERT INTO task_dependencies(task_id, dependency_id)
VALUES(
    $1, 
    $2
)
`

type CreateTaskDependencyParams struct {
	TaskID       uuid.UUID
	DependencyID uuid.UUID
}

func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, createTaskDependency, arg.TaskID, arg.DependencyID)
	return err
}

const getTaskDependenciesByTask = `-- name: GetTaskDependenciesByTask :many

SELECT task_id, dependency_id FROM task_dependencies
WHERE task_id = $1
`

func (q *Queries) GetTaskDependenciesByTask(ctx context.Context, taskID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDependenciesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDependency
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(&i.TaskID, &i.DependencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
