// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_dependencies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTaskDependency = `-- name: CreateTaskDependency :exec

INSERT INTO task_dependencies(task_id, dependency_id)
VALUES(
    $1, 
    $2
)
`

type CreateTaskDependencyParams struct {
	TaskID       uuid.UUID
	DependencyID uuid.UUID
}

func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, createTaskDependency, arg.TaskID, arg.DependencyID)
	return err
}
