// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one

INSERT INTO tasks(id, created_at, updated_at, description, domain_id, assignee_id)
VALUES(
    GEN_RANDOM_UUID(),
    NOW(), 
    NOW(), 
    $1, 
    $2,
    $3
)
RETURNING id, created_at, updated_at, description, domain_id, assignee_id, completed_at
`

type CreateTaskParams struct {
	Description string
	DomainID    uuid.UUID
	AssigneeID  uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Description, arg.DomainID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.DomainID,
		&i.AssigneeID,
		&i.CompletedAt,
	)
	return i, err
}
