// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one

INSERT INTO tasks(id, created_at, updated_at, description, domain_id, assignee_id)
VALUES(
    GEN_RANDOM_UUID(),
    NOW(), 
    NOW(), 
    $1, 
    $2,
    $3
)
RETURNING id, created_at, updated_at, description, domain_id, assignee_id, completed_at
`

type CreateTaskParams struct {
	Description string
	DomainID    uuid.UUID
	AssigneeID  uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Description, arg.DomainID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.DomainID,
		&i.AssigneeID,
		&i.CompletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one

SELECT id, created_at, updated_at, description, domain_id, assignee_id, completed_at FROM tasks 
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.DomainID,
		&i.AssigneeID,
		&i.CompletedAt,
	)
	return i, err
}

const getTasksOfDomain = `-- name: GetTasksOfDomain :many

SELECT id, created_at, updated_at, description, domain_id, assignee_id, completed_at FROM tasks 
WHERE domain_id = $1
`

func (q *Queries) GetTasksOfDomain(ctx context.Context, domainID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksOfDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.DomainID,
			&i.AssigneeID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnblockedUserTasks = `-- name: GetUnblockedUserTasks :many

WITH incomplete_dependencies AS (
    SELECT task_dependencies.task_id FROM tasks JOIN task_dependencies
    ON tasks.id = task_dependencies.dependency_id
    WHERE tasks.completed_at IS NULL
)
SELECT tasks.id, tasks.created_at, tasks.updated_at, tasks.description, tasks.domain_id, tasks.assignee_id, tasks.completed_at FROM tasks
WHERE tasks.id NOT IN (SELECT task_id FROM incomplete_dependencies)
AND tasks.assignee_id = $1
`

func (q *Queries) GetUnblockedUserTasks(ctx context.Context, assigneeID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getUnblockedUserTasks, assigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.DomainID,
			&i.AssigneeID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
