// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users(id, created_at, updated_at, email, display_name)
VALUES(
    GEN_RANDOM_UUID(), 
    NOW(), 
    NOW(), 
    $1, 
    $2
)
RETURNING id, created_at, updated_at, email, display_name
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const getUsersOfDomain = `-- name: GetUsersOfDomain :many

SELECT users.id, users.created_at, users.updated_at, users.email, users.display_name 
FROM users JOIN domains_users 
ON users.id = domains_users.user_id
WHERE domain_id = $1
`

func (q *Queries) GetUsersOfDomain(ctx context.Context, domainID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersOfDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
